suite: GPG secret template (signing disabled)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/secret_gpg.yaml
tests:
  - it: renders nothing
    set:
      secrets.gpg.enabled: false
    asserts:
      - hasDocuments:
          count: 0
