suite: Test gpg secret with signing disabled
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/secret_gpg.yaml
tests:
  - it: "Skip rendering when signing is disabled"
    set:
      secrets.gpg.enabled: false
    asserts:
      - hasDocuments:
          count: 0
