suite: Test dependency customization integrity of valkey
release:
  name: gitea-unittests
  namespace: testing
set:
  valkey:
    enabled: true
    auth:
      enabled: true
      aclUsers:
        default:
          permissions: "~* &* +@all"
          password: gitea-password
tests:
  - it: "[valkey] Apply valkey.auth.aclUsers.default.password"
    template: charts/valkey/templates/secret.yaml
    asserts:
      - documentIndex: 0
        equal:
          path: data.default-password
          value: "Z2l0ZWEtcGFzc3dvcmQ="
  - it: "[valkey] Render the referenced Service"
    template: charts/valkey/templates/service.yaml
    asserts:
      - containsDocument:
          kind: Service
          apiVersion: v1
          name: gitea-unittests-valkey
      - documentIndex: 0
        contains:
          path: spec.ports
          content:
            name: tcp
            port: 6379
            targetPort: tcp
            protocol: TCP
  - it: "[gitea] Wait for valkey to be up and running"
    template: templates/secret_init.yaml
    asserts:
      - documentIndex: 0
        matchRegex:
          path: data["configure_gitea.sh"]
          decodeBase64: true
          pattern: nc -vz -w2 gitea-unittests-valkey.testing.svc.cluster.local 6379
  - it: "[gitea] Wait for valkey to be up and running with a custom cluster domain"
    set:
      clusterDomain: my-special-cluster.local
    template: templates/secret_init.yaml
    asserts:
      - documentIndex: 0
        matchRegex:
          path: data["configure_gitea.sh"]
          decodeBase64: true
          pattern: nc -vz -w2 gitea-unittests-valkey.testing.svc.my-special-cluster.local 6379
