suite: Dependency checks | Major image bumps
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "[postgresql-ha] ensures we detect major image version upgrades"
    template: charts/postgresql-ha/templates/postgresql/statefulset.yaml
    set:
      postgresql:
        enabled: false
      postgresql-ha:
        enabled: true
    asserts:
      - documentIndex: 0
        matchRegex:
          path: spec.template.spec.containers[0].image
          # IN CASE OF AN INTENTIONAL MAJOR BUMP, ADJUST THIS TEST
          pattern: bitnamilegacy/postgresql-repmgr:17.+$
  - it: "[postgresql] ensures we detect major image version upgrades"
    template: charts/postgresql/templates/primary/statefulset.yaml
    set:
      postgresql:
        enabled: true
      postgresql-ha:
        enabled: false
    asserts:
      - documentIndex: 0
        matchRegex:
          path: spec.template.spec.containers[0].image
          # IN CASE OF AN INTENTIONAL MAJOR BUMP, ADJUST THIS TEST
          pattern: bitnamilegacy/postgresql:17.+$
  - it: "[valkey-cluster] ensures we detect major image version upgrades"
    template: charts/valkey-cluster/templates/valkey-statefulset.yaml
    set:
      valkey-cluster:
        enabled: true
      valkey:
        enabled: false
    asserts:
      - documentIndex: 0
        matchRegex:
          path: spec.template.spec.containers[0].image
          # IN CASE OF AN INTENTIONAL MAJOR BUMP, ADJUST THIS TEST
          pattern: bitnamilegacy/valkey-cluster:8.+$
  - it: "[valkey] ensures we detect major image version upgrades"
    template: charts/valkey/templates/primary/application.yaml
    set:
      valkey-cluster:
        enabled: false
      valkey:
        enabled: true
    asserts:
      - documentIndex: 0
        matchRegex:
          path: spec.template.spec.containers[0].image
          # IN CASE OF AN INTENTIONAL MAJOR BUMP, ADJUST THIS TEST
          pattern: bitnamilegacy/valkey:8.+$
