suite: Test dependency major image bumps
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "[valkey] Detect major image version upgrades"
    template: charts/valkey/templates/deploy_valkey.yaml
    set:
      valkey:
        enabled: true
    asserts:
      - documentIndex: 0
        matchRegex:
          path: spec.template.spec.containers[0].image
          # IN CASE OF AN INTENTIONAL MAJOR BUMP, ADJUST THIS TEST
          pattern: valkey/valkey:9.+$
