suite: Test metrics secret with monitoring disabled
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/secret_metrics.yaml
tests:
  - it: "Skip rendering when monitoring is disabled and gitea.metrics.token is empty"
    set:
      gitea.metrics.enabled: false
      gitea.metrics.serviceMonitor.enabled: false
      gitea.metrics.token: ""
    asserts:
      - hasDocuments:
          count: 0
  - it: "Skip rendering when monitoring is disabled and gitea.metrics.token is not empty"
    set:
      gitea.metrics.enabled: false
      gitea.metrics.serviceMonitor.enabled: false
      gitea.metrics.token: "test-token"
    asserts:
      - hasDocuments:
          count: 0
