suite: Check if actions raises an error
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: fails when trying to configure actions due to removal
    set:
      actions:
        enabled: true
    asserts:
      - failedTemplate:
          errorMessage: The actions sub-chart has been outsourced to a dedicated chart available at https://gitea.com/gitea/helm-actions. For assistance with the migration process, check https://gitea.com/gitea/helm-actions/issues/9.
