suite: Values conflicting checks
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: fails when trying to configure valkey and valkey-cluster the same time
    set:
      valkey-cluster:
        enabled: true
      valkey:
        enabled: true
    asserts:
      - failedTemplate:
          errorMessage: valkey and valkey-cluster cannot be enabled at the same time. Please only choose one.
