suite: Test init directory structure script for the rootless image
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/secret_init.yaml
tests:
  - it: "Run gpg in batch mode"
    set:
      secrets.gpg.enabled: true
      secrets.gpg.new.privateKey: |-
        -----BEGIN PGP PRIVATE KEY BLOCK-----
        {placeholder}
        -----END PGP PRIVATE KEY BLOCK-----
    asserts:
      - equal:
          path: data["configure_gpg_environment.sh"]
          decodeBase64: true
          value: |
            #!/usr/bin/env bash
            set -eu

            gpg --batch --import "$TMP_RAW_GPG_KEY"
  - it: "Skip the gpg script block when signing is disabled"
    asserts:
      - equal:
          path: data["init_directory_structure.sh"]
          decodeBase64: true
          value: |-
            #!/usr/bin/env bash

            set -euo pipefail
            mkdir -pv /data/git/.ssh
            chmod -Rv 700 /data/git/.ssh
            [ ! -d /data/gitea/conf ] && mkdir -pv /data/gitea/conf

            # prepare temp directory structure
            mkdir -pv "${GITEA_TEMP}"
            chmod -v ug+rwx "${GITEA_TEMP}"
  - it: "Add the gpg script block when signing is enabled"
    set:
      secrets.gpg.enabled: true
      secrets.gpg.new.privateKey: |-
        -----BEGIN PGP PRIVATE KEY BLOCK-----
        {placeholder}
        -----END PGP PRIVATE KEY BLOCK-----
    asserts:
      - equal:
          path: data["init_directory_structure.sh"]
          decodeBase64: true
          value: |-
            #!/usr/bin/env bash

            set -euo pipefail
            mkdir -pv /data/git/.ssh
            chmod -Rv 700 /data/git/.ssh
            [ ! -d /data/gitea/conf ] && mkdir -pv /data/gitea/conf

            # prepare temp directory structure
            mkdir -pv "${GITEA_TEMP}"
            chmod -v ug+rwx "${GITEA_TEMP}"

            if [ ! -d "${GNUPGHOME}" ]; then
              mkdir -pv "${GNUPGHOME}"
              chmod -v 700 "${GNUPGHOME}"
              chown -v 1000:1000 "${GNUPGHOME}"
            fi
  - it: "Skip the chown of /data even when image.fullOverride is set"
    template: templates/secret_init.yaml
    set:
      deployment.gitea.image.fullOverride: docker.gitea.com/gitea:1.20.5
    asserts:
      - equal:
          path: data["init_directory_structure.sh"]
          decodeBase64: true
          value: |-
            #!/usr/bin/env bash

            set -euo pipefail
            mkdir -pv /data/git/.ssh
            chmod -Rv 700 /data/git/.ssh
            [ ! -d /data/gitea/conf ] && mkdir -pv /data/gitea/conf

            # prepare temp directory structure
            mkdir -pv "${GITEA_TEMP}"
            chmod -v ug+rwx "${GITEA_TEMP}"
  - it: "Render data instead of stringData so removed keys are pruned on upgrade"
    asserts:
      - notExists:
          path: stringData
      - exists:
          path: data["init_directory_structure.sh"]
