chart:
  appVersion: 1.27.3 # renovate: datasource=docker registryUrl=https://docker.gitea.com depName=gitea
release:
  name: gitea-unittests
  namespace: testing
suite: PVC template
templates:
  - templates/gitea/persistentVolumeClaim.yaml
tests:
  - it: Skip persistentVolumeClaim if persistentVolumeClaim is disabled
    set:
      persistence.enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: Render persistentVolumeClaim with default values
    set:
      persistence.enabled: true
      persistence.new.storageClassName: "my-storage-class"
    asserts:
      - containsDocument:
          apiVersion: v1
          kind: PersistentVolumeClaim
          name: gitea-unittests
          namespace: testing
      - equal:
          path: spec.storageClassName
          value: "my-storage-class"
