chart:
  appVersion: 1.27.3
release:
  name: gitea-unittests
  namespace: testing
suite: Test persistentVolumeClaim storage class
templates:
  - templates/persistentVolumeClaim.yaml
tests:
  - it: "Render the storageClassName when persistence.new.storageClassName is defined"
    set:
      persistence.enabled: true
      persistence.new.storageClassName: my-storage-class
    asserts:
      - equal:
          path: spec.storageClassName
          value: my-storage-class
