suite: deployment template
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/deployment.yaml
  - templates/config.yaml
tests:
  - it: Render the deployment (default)
    asserts:
      - hasDocuments:
          count: 1
        template: templates/deployment.yaml
      - lengthEqual:
          path: spec.template.spec.initContainers
          count: 3
        template: templates/deployment.yaml

  - it: Render the deployment (signing)
    set:
      signing.enabled: true
    asserts:
      - hasDocuments:
          count: 1
        template: templates/deployment.yaml
      - lengthEqual:
          path: spec.template.spec.initContainers
          count: 4
        template: templates/deployment.yaml

  - it: Render the deployment (extraInitContainers)
    set:
      postExtraInitContainers:
        - name: foo
          image: docker.io/library/busybox:latest
      preExtraInitContainers:
        - name: bar
          image: docker.io/library/busybox:latest
      signing.enabled: true
    asserts:
      - hasDocuments:
          count: 1
        template: templates/deployment.yaml
      - lengthEqual:
          path: spec.template.spec.initContainers
          count: 6
        template: templates/deployment.yaml
      - contains:
          path: spec.template.spec.initContainers
          content:
            name: foo
            image: docker.io/library/busybox:latest
        template: templates/deployment.yaml
      - contains:
          path: spec.template.spec.initContainers
          content:
            name: bar
            image: docker.io/library/busybox:latest
        template: templates/deployment.yaml
