suite: deployment template (signing enabled)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/deployment.yaml
  - templates/secret_admin.yaml
  - templates/secret_config.yaml
  - templates/secret_gpg.yaml
  - templates/secret_init.yaml
  - templates/secret_inlineConfig.yaml
  - templates/secret_metrics.yaml
tests:
  - it: adds gpg init container
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.existingSecret.enabled: true
      secrets.gpg.existingSecret.secretName: "custom-gpg-secret"
    asserts:
      - equal:
          path: spec.template.spec.initContainers[2].name
          value: configure-gpg
      - equal:
          path: spec.template.spec.initContainers[2].command
          value: ["/usr/sbinx/configure_gpg_environment.sh"]
      - equal:
          path: spec.template.spec.initContainers[2].securityContext
          value:
            runAsUser: 1000
      - equal:
          path: spec.template.spec.initContainers[2].env
          value:
            - name: GNUPGHOME
              valueFrom:
                secretKeyRef:
                  name: custom-gpg-secret
                  key: gpgHome
            - name: TMP_RAW_GPG_KEY
              value: /raw/private.asc
      - equal:
          path: spec.template.spec.initContainers[2].volumeMounts
          value:
            - name: init
              mountPath: /usr/sbinx
            - name: data
              mountPath: /data
            - name: gpg-private-key
              mountPath: /raw
              readOnly: true
  - it: adds gpg env in `init-directories` init container
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.existingSecret.enabled: true
      secrets.gpg.existingSecret.secretName: "custom-gpg-secret"
    asserts:
      - contains:
          path: spec.template.spec.initContainers[0].env
          content:
            name: GNUPGHOME
            valueFrom:
              secretKeyRef:
                name: custom-gpg-secret
                key: gpgHome
  - it: adds gpg env in runtime container
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.existingSecret.enabled: true
      secrets.gpg.existingSecret.secretName: "custom-gpg-secret"
    asserts:
      - contains:
          path: spec.template.spec.containers[0].env
          content:
            name: GNUPGHOME
            valueFrom:
              secretKeyRef:
                name: custom-gpg-secret
                key: gpgHome
  - it: reads the gpg home from the configured key of an existing secret
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.existingSecret.enabled: true
      secrets.gpg.existingSecret.secretName: "custom-gpg-secret"
      secrets.gpg.existingSecret.gpgHomeKey: custom-gpg-home
    asserts:
      - contains:
          path: spec.template.spec.containers[0].env
          content:
            name: GNUPGHOME
            valueFrom:
              secretKeyRef:
                name: custom-gpg-secret
                key: custom-gpg-home
  - it: adds gpg volume spec
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.new.privateKey: "gpg-key-placeholder"
    asserts:
      - contains:
          path: spec.template.spec.volumes
          content:
            name: gpg-private-key
            secret:
              secretName: gitea-unittests-gpg-key
              items:
                - key: privateKey
                  path: private.asc
              defaultMode: 0100
  - it: supports gpg volume spec with external reference
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: true
      secrets.gpg.existingSecret.enabled: true
      secrets.gpg.existingSecret.secretName: custom-gpg-secret
      secrets.gpg.existingSecret.privateKeyKey: custom-private-key
    asserts:
      - contains:
          path: spec.template.spec.volumes
          content:
            name: gpg-private-key
            secret:
              secretName: custom-gpg-secret
              items:
                - key: custom-private-key
                  path: private.asc
              defaultMode: 0100
