suite: Test deployment with signing disabled
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/deployment.yaml
  - templates/secret_admin.yaml
  - templates/secret_config.yaml
  - templates/secret_gpg.yaml
  - templates/secret_init.yaml
  - templates/secret_inlineConfig.yaml
  - templates/secret_metrics.yaml
tests:
  - it: "Skip the gpg init container"
    template: templates/deployment.yaml
    asserts:
      - notContains:
          path: spec.template.spec.initContainers
          any: true
          content:
            name: configure-gpg
  - it: "Skip the gpg env of the `init-directories` init container"
    template: templates/deployment.yaml
    set:
      secrets.gpg.enabled: false
    asserts:
      - notContains:
          path: spec.template.spec.initContainers[0].env
          content:
            name: GNUPGHOME
  - it: "Skip the gpg env of the runtime container"
    template: templates/deployment.yaml
    asserts:
      - notContains:
          path: spec.template.spec.containers[0].env
          content:
            name: GNUPGHOME
  - it: "Skip the gpg volume spec"
    template: templates/deployment.yaml
    asserts:
      - notContains:
          path: spec.template.spec.volumes
          content:
            name: gpg-private-key
