{{- if and (.Values.gitea.metrics.enabled) (.Values.gitea.metrics.serviceMonitor.enabled) (.Values.gitea.metrics.token) (not .Values.secrets.metrics.existingSecret.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "gitea.secret.metrics.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitea.secret.metrics.labels" . | nindent 4 }}
  name: {{ include "gitea.secret.metrics.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.gitea.metrics.token  | b64enc }}
{{- end }}