suite: ServiceMonitor template (monitoring disabled)
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/serviceMonitor.yaml
tests:
  - it: "Skip rendering when the ServiceMonitor is disabled and gitea.metrics.token is empty"
    set:
      gitea.metrics.enabled: false
      gitea.metrics.token: ""
      gitea.metrics.serviceMonitor.enabled: false
    asserts:
      - hasDocuments:
          count: 0
  - it: "Skip rendering when the ServiceMonitor is disabled and gitea.metrics.token is not empty"
    set:
      gitea.metrics.enabled: false
      gitea.metrics.token: "test-token"
      gitea.metrics.serviceMonitor.enabled: false
    asserts:
      - hasDocuments:
          count: 0
