{{- if eq (include "gitea.persistentVolumeClaim.enabled" .) "true" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- with (include "gitea.persistentVolumeClaim.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- with (include "gitea.persistentVolumeClaim.labels" .) }}
  labels:
    {{- . | nindent 4 }}
  {{- end }}
  name: {{ include "gitea.persistentVolumeClaim.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  {{- if gt (.Values.deployment.replicas | int) 1 }}
      - ReadWriteMany
  {{- else }}
    {{- .Values.persistence.new.accessModes | toYaml | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.new.size }}
  {{- with .Values.persistence.new.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  volumeMode: Filesystem
  {{- with .Values.persistence.new.persistentVolumeName }}
  volumeName: {{ . }}
  {{- end }}
{{- end }}
