---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  name: {{ include "gitea.secret.inlineConfig.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  {{- include "gitea.inline_configuration" . | nindent 2 }}