{{- /* Evaluated outside of the Secret because it populates `.Values.gitea.config` for the other templates. */ -}}
{{- $inlineConfiguration := include "gitea.inline_configuration" . -}}
{{- if not .Values.secrets.inlineConfig.existingSecret.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "gitea.secret.inlineConfig.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitea.secret.inlineConfig.labels" . | nindent 4 }}
  name: {{ include "gitea.secret.inlineConfig.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  {{- $inlineConfiguration | nindent 2 }}
{{- end }}