---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-inline-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "gitea.inline_configuration" . | nindent 2 }}