{{- if and (.Values.secrets.admin.enabled) (not .Values.secrets.admin.existingSecret.enabled) -}}
{{- if or (empty .Values.secrets.admin.new.username) (empty .Values.secrets.admin.new.password) -}}
  {{- fail "Either specify `secrets.admin.new.username` and `secrets.admin.new.password` or reference an existing Secret via `secrets.admin.existingSecret`" -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "gitea.secret.admin.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitea.secret.admin.labels" . | nindent 4 }}
  name: {{ include "gitea.secret.admin.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  email: {{ .Values.secrets.admin.new.email | b64enc }}
  password: {{ .Values.secrets.admin.new.password | b64enc }}
  username: {{ .Values.secrets.admin.new.username | b64enc }}
{{- end }}
