{{- if and (.Values.secrets.gpg.enabled) (not .Values.secrets.gpg.existingSecret.enabled) -}}
{{- if empty .Values.secrets.gpg.new.privateKey -}}
  {{- fail "Either specify `secrets.gpg.new.privateKey` or reference an existing Secret via `secrets.gpg.existingSecret`" -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "gitea.secret.gpg.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitea.secret.gpg.labels" . | nindent 4 }}
  name: {{ include "gitea.secret.gpg.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  gpgHome: {{ .Values.secrets.gpg.new.gpgHome | b64enc }}
  privateKey: {{ .Values.secrets.gpg.new.privateKey | b64enc }}
{{- end }}
