suite: Test ingress.yaml
templates:
  - templates/gitea/ingress.yaml
tests:
  - it: should succeed when only ingress.className is defined
    template: templates/gitea/ingress.yaml
    set:
      ingress.enabled: true
      ingress.className: "ingress-class"
    asserts:
      - equal:
          path: spec.ingressClassName
          value: ingress-class

  - it: should succeed when only ingress.ingressClassName is defined
    template: templates/gitea/ingress.yaml
    set:
      ingress.enabled: true
      ingress.ingressClassName: "ingress-class"
    asserts:
      - equal:
          path: spec.ingressClassName
          value: ingress-class
