suite: Test ingress.yaml
templates:
  - templates/gitea/ingress.yaml
tests:
  - it: should fail when both ingress.className and ingress.ingressClassName are defined
    template: templates/gitea/ingress.yaml
    set:
      ingress:
        enabled: true
        className: ingress-class
        ingressClassName: ingress-class
    asserts:
      - failedTemplate:
          errorMessage: "ingress.ingressClassName and ingress.className cannot be defined at the same time. Please only choose one."

  - it: should succeed when only ingress.className is defined
    template: templates/gitea/ingress.yaml
    set:
      ingress.enabled: true
      ingress.className: "ingress-class"
    asserts:
      - equal:
          path: spec.ingressClassName
          value: ingress-class

  - it: should succeed when only ingress.ingressClassName is defined
    template: templates/gitea/ingress.yaml
    set:
      ingress.enabled: true
      ingress.ingressClassName: "ingress-class"
    asserts:
      - equal:
          path: spec.ingressClassName
          value: ingress-class
