suite: Test ingress with implicit path defaults
templates:
  - templates/gitea/ingress.yaml
tests:
  - it: should use default path and pathType when no paths are specified
    set:
      ingress.enabled: true
      ingress.hosts:
        - host: git.example.com
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Ingress
      - equal:
          path: spec.rules[0].host
          value: "git.example.com"
      - equal:
          path: spec.rules[0].http.paths[0].path
          value: "/"
      - equal:
          path: spec.rules[0].http.paths[0].pathType
          value: "Prefix"
