suite: Test ingress with structured paths
templates:
  - templates/gitea/ingress.yaml
tests:
  - it: should work with structured path definitions
    set:
      ingress.enabled: true
      ingress.hosts:
        - host: git.devxy.io
          paths:
            - path: /
              pathType: Prefix
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Ingress
      - equal:
          path: spec.rules[0].host
          value: "git.devxy.io"
      - equal:
          path: spec.rules[0].http.paths[0].path
          value: "/"
      - equal:
          path: spec.rules[0].http.paths[0].pathType
          value: "Prefix"