suite: Test config actions
release:
  name: gitea-unittests
  namespace: testing
templates:
  - templates/secret_inlineConfig.yaml
tests:
  - it: "Enable actions by default to match vanilla Gitea"
    template: templates/secret_inlineConfig.yaml
    asserts:
      - documentIndex: 0
        notExists:
          path: data.actions

  - it: "Disable actions via the inline config"
    template: templates/secret_inlineConfig.yaml
    set:
      gitea.config.actions.ENABLED: false
    asserts:
      - documentIndex: 0
        equal:
          path: data.actions
          decodeBase64: true
          value: |-
            ENABLED=false
