suite: Test config cache
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "Configure the cache for valkey"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: true
    asserts:
      - documentIndex: 0
        equal:
          path: data.cache
          decodeBase64: true
          value: |-
            ADAPTER=redis
            HOST=redis://:changeme@gitea-unittests-valkey.testing.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&

  - it: "Configure the cache for 'memory' when valkey is disabled"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: false
    asserts:
      - documentIndex: 0
        equal:
          path: data.cache
          decodeBase64: true
          value: |-
            ADAPTER=memory
            HOST=

  - it: "Customize the cache when valkey is disabled"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: false
      gitea.config.cache.ADAPTER: custom-adapter
      gitea.config.cache.HOST: custom-host
    asserts:
      - documentIndex: 0
        equal:
          path: data.cache
          decodeBase64: true
          value: |-
            ADAPTER=custom-adapter
            HOST=custom-host
