suite: Test config database
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "Connect to the read-write Service of the CloudNativePG Cluster"
    template: templates/secret_inlineConfig.yaml
    set:
      cloudnativePG:
        enabled: true
    asserts:
      - documentIndex: 0
        matchRegex:
          path: data.database
          decodeBase64: true
          pattern: HOST=gitea-unittests-postgresql-rw.testing.svc.cluster.local:5432

  - it: "Connect to the read-write Service of the CloudNativePG Cluster with a custom cluster domain"
    template: templates/secret_inlineConfig.yaml
    set:
      clusterDomain: my-special-cluster.local
      cloudnativePG:
        enabled: true
    asserts:
      - documentIndex: 0
        matchRegex:
          path: data.database
          decodeBase64: true
          pattern: HOST=gitea-unittests-postgresql-rw.testing.svc.my-special-cluster.local:5432

  - it: "Connect to the configured CloudNativePG database"
    template: templates/secret_inlineConfig.yaml
    set:
      cloudnativePG:
        enabled: true
        credentials:
          database: gitea-database
          username: gitea-username
    asserts:
      - documentIndex: 0
        equal:
          path: data.database
          decodeBase64: true
          value: |-
            DB_TYPE=postgres
            HOST=gitea-unittests-postgresql-rw.testing.svc.cluster.local:5432
            NAME=gitea-database
            USER=gitea-username
