suite: Test config session
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "Configure the session for valkey"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: true
    asserts:
      - documentIndex: 0
        equal:
          path: data.session
          decodeBase64: true
          value: |-
            PROVIDER=redis
            PROVIDER_CONFIG=redis://:changeme@gitea-unittests-valkey.testing.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&

  - it: "Configure the session for 'memory' when valkey is disabled"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: false
    asserts:
      - documentIndex: 0
        equal:
          path: data.session
          decodeBase64: true
          value: |-
            PROVIDER=memory
            PROVIDER_CONFIG=

  - it: "Customize the session when valkey is disabled"
    template: templates/secret_inlineConfig.yaml
    set:
      valkey:
        enabled: false
      gitea.config.session.PROVIDER: custom-provider
      gitea.config.session.PROVIDER_CONFIG: custom-provider-config
    asserts:
      - documentIndex: 0
        equal:
          path: data.session
          decodeBase64: true
          value: |-
            PROVIDER=custom-provider
            PROVIDER_CONFIG=custom-provider-config
